### ISSUE TITLE
Undefined "VisitState" function

### ISSUE THREAD

**Issue by bnjmnt4n** [jviereck/regjstraverse#1]
At [line #121](https://github.com/jviereck/regjstraverse/blob/master/index.js#L121), a function "VisitState" is called, but it has not been defined. IMO that’s a typo, and should be "TraverseState" instead.

**Comment by jviereck** [comment]
Oh boy, this is a really stupid mistake and I am so sorry you hit it :/ I fixed it, added a new unit test to cover this case and released version 0.1.1 on npm.
